### ISSUE TITLE
not calculating error correctly

### ISSUE THREAD

**Issue by finnpuschmann** [nicoco007/Propagation-of-Uncertainty-Calculator#36]
![Capture](https://user-images.githubusercontent.com/84124318/223786494-2b6a80db-e071-4834-bb36-07a1911899fd.PNG)

The Error seemed too high, so I zeroed out all the uncertainties and it gave me the same error. 

It gave me the same uncertainty for the actual errors of  delta(a)=0.001, delta(r)=0.0001, delta(m)=0.0001, delta(n)=0.0002 as the zeroed out errors (in the screen capture) gives me.

Calculating the Error by Hand gives me approx. 5.2*10^-6

**Comment by WalinCodeDump** [comment]
I had a similar error -- the formula for error appears to be correct, but in the second line you can see that when it's multiplying deltas by the partial derivatives, it doesn't group everything together with a parentheses.

![image](https://github.com/nicoco007/Propagation-of-Uncertainty-Calculator/assets/48355468/a4878aef-ff00-4d25-ada8-555fd8cb5688)



Here, the highlighted areas should be within a pair of parentheses. In the middle two (the blue ones) this isn't a problem because they're products. They don't need to be grouped, necessarily.

It's a problem for the left and right (the green ones) because they're sums. So the delta is multiplied by the right summand, and the left summand goes un-multiplied. That's why your error is nonzero despite setting all your deltas to zero.

---------
As for a solution, what works for me is encasing the whole formula in a pair of parentheses. So your formula, instead of being:

> J = (m \* (2\*a)^2)/12 + (4\*n\*r^2)/5 + 2\*n\*a^2

it should be:

> J = ((m \* (2\*a)^2)/12 + (4\*n\*r^2)/5 + 2\*n\*a^2)

(Put parentheses around the entire right-hand side of the equation, and this specific bug should go away).

Sorry this answer is so late; you probably worked it out yourself. I just ran into this problem earlier and looked for anyone who also experienced it, and you were the only one here who reported it.

**Comment by nicoco007** [comment]
I'm not sure how this wasn't caught earlier. Thanks for the report!
